// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shopping.ProductAPI.Model.Context;

#nullable disable

namespace Shopping.ProductAPI.Migrations
{
    [DbContext(typeof(SqlServerContext))]
    partial class SqlServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Shopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("category name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 3L,
                            CategoryName = "T-SHIRT",
                            Description = "LOREM SIAJSID OSDJOAJSD ",
                            ImageUrl = "https://www.pexels.com/pt-br/foto/roupas-variadas-996329/",
                            Name = "Camisa x",
                            Price = 45.4m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "T-SHIRT",
                            Description = "LOREM SIAJSID OSDJOyyyAJSD ",
                            ImageUrl = "https://www.pexels.com/pt-br/foto/roupas-variadas-996329/",
                            Name = "Camisa yx",
                            Price = 48.4m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "T-SHIRT",
                            Description = "LOREM SIAJSID OSDJeteOAJSD ",
                            ImageUrl = "https://www.pexels.com/pt-br/foto/traje-casual-roupas-trajes-espaco-do-texto-9558699/",
                            Name = "Camisa bfgx",
                            Price = 49.4m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "T-SHIRT",
                            Description = "LOREM SIAJSID OfgsdfdSDJOAJSD ",
                            ImageUrl = "https://www.pexels.com/pt-br/foto/roupas-variadas-996329/",
                            Name = "Camisa dsfdx",
                            Price = 42.4m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
